
# -*- coding: utf-8 -*-
"""fundi_rates_chart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QkTE6-bx-1enrFVTQFepMlHc6kEbkGE
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("funding_rates.csv")

print(df['funding_time'])

plt.plot(df['funding_time'], df['funding_rate'])
plt.title("BTC Funding Rate(BINANCE)")
plt.xlabel("Time")
plt.ylabel("Funding Rate")

plt.show()

df.describe()

# 평균 펀딩비 최댓값, 최솟값 등을 출력해주는 함수

df_unique = df.drop_duplicates(subset="funding_time")
print(df_unique)

# df_unique => dataset 에서 중복 제거

upper = df_unique['funding_rate'].quantile(0.95)
lower = df_unique['funding_rate'].quantile(0.05)

extreme = df_unique[(df_unique['funding_rate'] > upper) | (df_unique['funding_rate'] < lower)]

# 극단값 출력하기

plt.figure(figsize=(12,5))
plt.plot(df_unique['funding_time'], df_unique['funding_rate'])
plt.scatter(extreme['funding_time'], extreme['funding_rate'], color='red')
plt.title("Extreme Funding Rates")
plt.show()

df['funding_change'] = df['funding_rate'].diff()
plt.plot(df["funding_time"], df["funding_change"])

